# Generated by Django 2.1.1 on 2018-09-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_system',
            new_name='is_staff',
        ),
    ]
